# Generated by Django 3.1 on 2021-03-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210319_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
