# Generated by Django 3.1 on 2021-03-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210319_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
